# Reads CSV output files generated by scheduling simulations
# Computes throughput for each scheduling algorithm
# Used as input for plotting and performance comparison graphs
import pandas as pd
import glob
import os

INPUT_DIR = "results"
OUTPUT_FILE = "results/summary_throughput.csv"

results = []

# Find all algorithm output files
files = glob.glob(os.path.join(INPUT_DIR, "output_*.csv"))

for file in files:
    df = pd.read_csv(file)

    # Safety: remove any empty rows
    df = df.dropna()

    # Sort by time just in case
    df = df.sort_values("CompletionTime")

    # Extract algorithm name from filename
    algo = os.path.basename(file).replace("output_", "").replace(".csv", "")

    # If RunID exists, treat each RunID as a separate experiment
    if "RunID" in df.columns:
        grouped = df.groupby("RunID")
    else:
        grouped = [("all", df)]

    for run_id, run_data in grouped:

        if len(run_data) == 0:
            continue

        start_time = run_data["ArrivalTime"].min()
        end_time = run_data["CompletionTime"].max()

        num_orders = len(run_data)
        runtime = end_time - start_time

        throughput = num_orders / runtime if runtime > 0 else 0

        results.append([
            algo,
            run_id,
            num_orders,
            runtime,
            throughput
        ])

# Convert to DataFrame
summary = pd.DataFrame(results, columns=[
    "Algorithm",
    "RunID",
    "OrdersCompleted",
    "Runtime(ms)",
    "Throughput"
])

# Save to CSV
summary.to_csv(OUTPUT_FILE, index=False)

print("Done!")
print("Saved to:", OUTPUT_FILE)